# Generated by Django 2.2 on 2019-04-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190415_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelManager',
        ),
    ]
