# Generated by Django 2.2 on 2019-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190415_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='questions.Question'),
        ),
    ]
