# Generated by Django 2.2 on 2019-04-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20190415_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='question',
        ),
    ]
